baseURL = 'https://spinach.blog'
languageCode = 'ko-kr'
title = 'Spinach'
theme = 'ananke'

enableEmoji = true
enableRobotTXT = true
disqusShortname = "spinachhh"
googleAnalytics = "G-RZ17MSRZ2G"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/gptjddldi"
color = '#76a9e7'